version: '3'
services:
  webserver:
    build:
      context: ./
      dockerfile: docker/webserver.dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    links:
      - app
    depends_on:
      - app

  app:
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    volumes:
      - ./:/var/www
    links:
      - mariadb
    depends_on:
      - mariadb
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mariadb"

  mariadb:
    image: mariadb
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=wehaveitall"
      - "MYSQL_USER=***USER AQUI***"
      - "MYSQL_PASSWORD=***PASS AQUI***"
    ports:
      - "3306:3306"